### ISSUE TITLE
login to nexus registry gives 404

### ISSUE THREAD

**Issue by elntagka** [larscheid-schmitzhermes/nexus3-github-oauth-plugin#22] opened 2018-03-06 15:41 UTC
Hi, is it possible to authenticate against a nexus hosted registry using this plugin?
Currently I can successfully login on the console but docker login returns 404.

**Comment by schmitzhermes** [comment] 2018-03-06 17:52
Hey, I am not quite sure if I understand your question correctly. 
This plugin allows a user to authenticate via Github via a self-hosted Nexus instance (the docker image would be `sonatype/nexus3:3.7.1`). To login, you need your github username and a personal access token with the scope `read:org`. It does not matter which type of registry you are using inside Nexus (hosted maven, Docker, npm, ...) 

Does this answer your question?

**Comment by elntagka** [comment] 2018-03-06 18:42
Hey, thanks for the swift response. 
I have setup a Docker repo in my nexus 3 and in order to push and pull images from it I need to authenticate. This works fine without the plugin & users set locally on the nexus instance (vanilla nexus3) but when I use the plugin I get 404. 
The command I’m trying for example looks like the below:
docker login <my_nexus_host>:<port_for_repo>
Does this plugin only support login via the nexus console?

**Comment by tobilarscheid** [comment] 2018-03-06 19:42
Did you configure the roles / privileges so your user is allowed to access to the docker repo? Can you post the GitHub plugin related log output of your nexus?

**Comment by elntagka** [comment] 2018-03-06 20:30
Hey, yes I’ve configured the role with admin permissions and they are granted successfully to the user when logging via the console. Please can you let me know what is the log file for the plugin? I can see plugin related logs in the nexus.log file when I login/log-gout from the console but nothing when I try the Docker login. In the request.log I can see the request and that it got 404.

**Comment by tobilarscheid** [comment] 2018-03-07 12:09
All plugin logs go to the nexus.log file. It's really strange that the plugin is not triggered for a docker login - indeed I just tried it myself for a nexus3 installation and I can reproduce your error!

**Comment by elntagka** [comment] 2018-03-07 13:25
thanks for reproducing @tobilarscheid! Any suggestions?

**Comment by tobilarscheid** [comment] 2018-03-07 14:05
well, honestly at this point my only suggestion is researching how and why the nexus behaves differently on docker logins... seems like a bug to me!

**Comment by schmitzhermes** [comment] 2018-03-08 13:41
Well I just checked this and it worked. Our setup is slightly different though. In front of the Nexus we have a reverse proxy, that translates `<nexus-host>:<port>` to a different host, and we registered a DNS A-record for this host. Although this should not be the problem, this is the only difference I can spot right now. 

Can you maybe state what your `<nexus-host>` looks like?

**Comment by elntagka** [comment] 2018-03-08 15:26
hi @schmitzhermes, I have nexus configured behind an ELB (AWS) which gets https traffic and routes it to `http://<nexus-host>:<port>`

**Comment by schmitzhermes** [comment] 2018-03-08 16:16
Are you aware that the Docker registry runs on a _different_ port than the rest of Nexus?

**Comment by schmitzhermes** [comment] 2018-03-08 16:17
![image](https://user-images.githubusercontent.com/8810148/37162026-8367e042-22f4-11e8-8537-74153e66c464.png)
you need to setup this repository connector afaik - then point your AWS LB to this port and assign a different domain / route

**Comment by elntagka** [comment] 2018-03-08 16:19
@schmitzhermes yes of course. 
The docker login works fine when I don't have the plugin on nexus.

**Comment by schmitzhermes** [comment] 2018-03-08 16:22
could you pls state the _actual_ `docker login [URL]` command you use to login, i.e. also posting the URL (maybe obfuscate some at some unnecessary part if you don't want to have it on github)

**Comment by elntagka** [comment] 2018-03-08 16:28
Sure. I've setup a hosted registry with an http connector on 8083. My ELB is setup to get https requests on 8083 and transfer them to http 8083 to the nexus host.
So the command I'm using from my workstation is the below:   
`docker login https://nexus.tools.myorg.com:8083`

**Comment by tobilarscheid** [comment] 2018-03-26 08:18
@elntagka as you can see in #24 other people also report success for docker - I am therefore closing this issue for now. Feel free to reopen if you have any new information.

**Closed by tobilarscheid** 2018-03-26 08:18 UTC

**Comment by rlogiacco** [comment] 2022-02-18 07:39
almost 4 years later I have this exact same issue and I wasn't able to find a solution looking through the referenced #24 ... I hate commenting on hold issues, but I'm pretty sure if I opne a new one will be moved here, so I'm actually trying to facilitate everyone's life.
